apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: fusioniq
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bWJ5R1ZvPkJnN3M6cWhpYXZUW3ApLTpkdTJvZg==  # Base64 for password
  SPRING_DATASOURCE_USERNAME: YWRtaW4=  
