apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: fusioniq
type: Opaque
data:
  # SPRING_DATASOURCE_PASSWORD: fn43dFplMHAjTVhsNUIqRHdrUE9ZXzdNPFc0NA==  # Base64 for password
  # SPRING_DATASOURCE_USERNAME: YWRtaW4=  
