apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: fusioniq
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: TkVtI3NxaXdvLVY6RS4tSkZpPFVLKUV0cSFiOA==  # Base64 for password
  SPRING_DATASOURCE_USERNAME: YWRtaW4=  
